#this script was used to compute the quality (new metric designed by us) of the answers generated by the RAGs, on already computed answers.
#You shohuld use 'perform_cross_validation_evaluation.py' to compute the answers and the scores on the cross-validation dataset.


import os
from argparse import ArgumentParser

import numpy as np
from tqdm import tqdm

from CIT.evaluation.utils import (
    get_quality_from_question,
    load_jsonl,
    save_jsonl,
    save_mean_metrics,
)

parser= ArgumentParser(description="Compute quality from answers")
parser.add_argument("--answers_folder", type=str, default="./src/CIT/training/models/cv/data/test_answers/ft_20.5",
     help="Path to the answers file, with precision and recall calculated")

parser.add_argument("--answers_with_quality_folder", type=str, default="./src/CIT/training/models/cv/data/test_answers/ft_20.5",
     help="Path to the answers file, with precision and recall calculated")
parser.add_argument("--scores_folder", type=str, default="./src/CIT/training/models/cv/scores/ft_20.5",
     help="Path to save the quality results")
args = parser.parse_args()


if __name__ == "__main__":


    # Load the answers from the specified path
    answers_path = args.answers_folder
    if not os.path.exists(answers_path):
        raise FileNotFoundError(f"The specified answers file does not exist: {answers_path}")
    
    scores_folder = args.scores_folder
    if not os.path.exists(scores_folder):
        os.makedirs(scores_folder)

    answers_with_quality_folder = args.answers_with_quality_folder
    if not os.path.exists(answers_with_quality_folder):
        os.makedirs(answers_with_quality_folder)


    listdir = os.listdir(answers_path)
    listdir_sorted = sorted(listdir, key=lambda x: int(x.split('fold_')[-1].split('.')[0]))  # Sort by fold number
    
    
    for file in listdir_sorted:
        if file.endswith(".jsonl"):
            answers_fold=load_jsonl(os.path.join(answers_path, file))  
            quality_results = []
            for answer in tqdm(answers_fold):
                quality = get_quality_from_question(answer)
                answer['quality'] = quality
                quality_results.append(answer)
            hallucinations_urls=["yes" for a in quality_results if a["hallucination"]]
            scores_file_name=file.replace("answers", "scores")
            scores_path= os.path.join(scores_folder, scores_file_name)
            save_mean_metrics(quality_results,hallucinations_urls,scores_path=scores_path)
            save_jsonl(os.path.join(answers_with_quality_folder, file), quality_results)
            print(f"Processed {file}: {len(quality_results)} answers with quality scores.")

    

    #load all scores and put them in a single file
    all_scores_path=os.path.join(scores_folder, "all_scores.jsonl")
    all_scores=[]
    files_scores = os.listdir(scores_folder)
    files_sorted = sorted(files_scores, key=lambda x: int(x.split("scores_fold_")[1].split(".")[0]) if "scores_fold_" in x else float('inf'))
    for scores_file in files_sorted:
        if scores_file.endswith(".jsonl") and scores_file != "all_scores.jsonl":
            score_fold=load_jsonl(os.path.join(scores_folder, scores_file))
            all_scores.extend(score_fold)

    #compute mean and std of the scores
    mean_scores = {}
    keys_metrics = all_scores[0].keys()
    for key in keys_metrics:
        scores = [score[key] for score in all_scores]
        mean_score = np.mean(scores)
        std_score = np.std(scores)
        mean_scores[key] = {
            "mean":np.round(mean_score, 2),
            "std": np.round(std_score, 2)
        }
    all_scores.append(mean_scores)

    save_jsonl(all_scores_path, all_scores)
    print(f"All scores saved in {all_scores_path}")

